### ISSUE TITLE
Fell out of stackage

### ISSUE THREAD

**Issue by nomeata** [jwiegley/gitlib#65]
The gitlib packages are no longer in stackage:
https://github.com/fpco/stackage/blob/master/build-constraints.yaml

@borsboom, it would be nice to have them back in.

Related:
- https://github.com/bos/text-icu/issues/24
- https://github.com/cgaebel/stm-conduit/issues/39

**Comment by borsboom** [comment]
Stackage nightly recently switched to GHC 8.0.1, which forced any package that didn't build to be disabled.  See [this blog post](https://www.fpcomplete.com/blog/2016/05/moving-stackage-nightly-ghc-8).
  
I actually took on Stackage "maintainership" of gitlib because we needed it for a project, but we're not using it anymore.  As such, I'd rather pass that maintainership over to someone else (like you, if you want it).  The deal is basically that once it's confirmed that gitlib is compatible with the latest Stackage nightlies, you just submit a PR to the build constraints adding it back in.  You can check compatibility using `stack init --resolver nightly --force` and then make sure it builds and tests pass.  See the aforementioned blog post for more details.

**Comment by nomeata** [comment]
Also, at least ` gitlib-libgit2` needs more than just version bumps

```
--  While building package gitlib-libgit2-2.2.0.1 using:
      /home/travis/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/travis/build/nomeata/gipeda/.stack-work/logs/gitlib-libgit2-2.2.0.1.log
    Configuring gitlib-libgit2-2.2.0.1...
    Building gitlib-libgit2-2.2.0.1...
    Preprocessing library gitlib-libgit2-2.2.0.1...
    [1 of 5] Compiling Git.Libgit2.Types ( Git/Libgit2/Types.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Git/Libgit2/Types.o )
    
    /tmp/stack10478/gitlib-libgit2-2.2.0.1/Git/Libgit2/Types.hs:51:21: error:
        Not in scope: type constructor or class ‘MonadThrow'
```

I’m not too keen on becoming the gitlib maintainer myself, although I do use it in a project of mine (gipeda, which runs http://perf.haskell.org).

**Comment by borsboom** [comment]
It's ideal if a package's own maintainer is also its maintainer in Stackage, but not required.  I'm not a gitlib maintainer either.

**Comment by jwiegley** [comment]
@nomeata This has been building for me with GHC 8.0.2, are you still having problems?
